name: Publish & Deploy New Build
on: [push]

jobs:
  push_to_registry:
    name: Expense Tracker Pipeline
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Check out GitHub repo
        uses: actions/checkout@v2

      - name: Checking
        run: |
          echo "${{ secrets.MY_GLOBAL_SECRET }}"
          echo "${{ secrets.MY_SECRET }}"
